id: P010640
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:17:44.020221
source_metadata:
  id: bdr:W20487
  title: སློབ་དཔོན་དབྱུག་པ་ཅན་གྱིས་མཛད་པ་སོགས་སྙན་ངག་གི་སྐོར།
  author: ''
  volumes:
    e03d4a21287141c581a67f50922daccd:
      image_group_id: I4648
      title: ''
      volume_number: 1
      total_pages: 700
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
